name: axons_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.3
  flutter_secure_storage: ^8.0.0
  flutter_bloc: ^8.1.3
  dio: ^5.3.0
  equatable: ^2.0.5
  easy_localization: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - assets/launcher/

  fonts:
    - family: IBMPlexSansThai
      fonts:
        - asset: assets/fonts/IBMPlexSansThai-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/IBMPlexSansThai-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSansThai-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSansThai-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSansThai-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSansThai-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/launcher/app_icon.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21

